package practice.semo.comment;


import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import practice.semo.post.PostRepository;
import practice.semo.post.PostTable2;

@Service
@RequiredArgsConstructor
public class CommentService {

    private final CommentRepository commentRepository;
    private final PostRepository postRepository;


    public void commentWrite(Long post_id ,String content) {

        PostTable2 post = postRepository.findById(post_id)
                .orElseThrow(()-> new IllegalArgumentException("NO POST ID"));

        CommentTable2 table = new CommentTable2();
        table.setPost(post);
        table.setContent(content);
        commentRepository.save(table);
    }

    public int autoWrite(Long post_id) {
        PostTable2 post = postRepository.findById(post_id)
                .orElseThrow(() -> new IllegalArgumentException("NO POST ID AUTO"));

        for (int i = 0; i < 5000; i++) {
            CommentTable2 table = new CommentTable2();
            String autoGeneratedContent = (i + 1) + "번째 댓글 작성";

            table.setPost(post);
            table.setContent(autoGeneratedContent);
            commentRepository.save(table);
        }

        return 5000;  // 작성된 댓글 수 반환
    }
}
